import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, CalendarDays, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/portal/AppShell";
import { ServiceCatalogue } from "@/components/portal/ServiceCatalogue";
import { STORE_FORMATS } from "@/lib/portal/data";
export const Route = createFileRoute("/ads")({head:()=>({meta:[{title:"Главная — Евроторг Media"},{name:"description",content:"Рекламные услуги, торговые объекты и заявки сети Евроторг."},{property:"og:title",content:"Евроторг Media — главная"},{property:"og:description",content:"Выберите рекламные услуги и торговые объекты Евроторга."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:AdsPage});
function AdsPage(){const [where,setWhere]=useState("");const [format,setFormat]=useState("");const [date,setDate]=useState("");return <AppShell>
  <section className="flex min-h-[320px] flex-col items-center justify-center bg-muted px-6 py-12 text-center"><h1 className="max-w-2xl text-3xl font-extrabold uppercase leading-tight sm:text-5xl">Какой ТО продаст ваш рекламный текст</h1><div className="mt-8 flex flex-wrap justify-center gap-3"><Button size="lg" asChild><Link to="/services">Заказать рекламные услуги</Link></Button><Button size="lg" variant="secondary" asChild><Link to="/stores" search={{ query: "", format: "" }}>Выбрать торговые объекты</Link></Button></div></section>
  <div className="mt-8 grid gap-2 rounded border border-foreground p-2 md:grid-cols-[1fr_1fr_1fr_auto]"><label className="relative"><span className="sr-only">Где разместить рекламу?</span><input value={where} onChange={(e)=>setWhere(e.target.value)} placeholder="Где разместить рекламу?" className="w-full border-0 px-4 py-2 text-sm"/><ChevronDown className="pointer-events-none absolute right-3 top-2.5 size-4"/></label><label className="relative"><span className="sr-only">Формат торгового объекта</span><select value={format} onChange={(e)=>setFormat(e.target.value)} className="w-full border-0 px-4 py-2 text-sm"><option value="">Какие форматы использовать?</option>{STORE_FORMATS.map((f)=><option key={f}>{f}</option>)}</select></label><label className="relative flex items-center"><CalendarDays className="ml-3 size-4"/><span className="sr-only">Когда?</span><input type="date" value={date} onChange={(e)=>setDate(e.target.value)} className="min-w-0 flex-1 border-0 px-3 py-2 text-sm"/></label><Button asChild><Link to="/stores" search={{ query: where, format }}>Подобрать объекты <ArrowRight /></Link></Button></div>
  <section className="mt-14"><div className="mb-6 flex items-center justify-between gap-4"><h2 className="text-2xl font-bold">Рекламные услуги</h2><Button size="sm" variant="secondary" asChild><Link to="/services">Показать все форматы</Link></Button></div><ServiceCatalogue compact /></section>
  <section className="mt-14 flex min-h-56 items-center justify-center bg-muted px-6 text-center"><div><h2 className="text-xl font-bold">Реклама в сети Евроторг</h2><p className="mt-2 text-sm text-muted-foreground">Выберите торговые объекты и рекламные форматы для своей кампании.</p><Button className="mt-5" asChild><Link to="/order" search={{ stores: "" }}>Оформить заявку</Link></Button></div></section>
</AppShell>}
