import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { ArrowLeft, Check, ChevronDown, ShoppingCart, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/portal/AppShell";
import { StorePicker } from "@/components/portal/StorePicker";
import { PLACEMENTS, STORES, formatMoney } from "@/lib/portal/data";
import { usePortal, type RequestItem } from "@/lib/portal/store";
import retailImage from "@/assets/retail-placement.jpg";
export const Route = createFileRoute("/order")({validateSearch:(search:Record<string,unknown>)=>({stores:typeof search.stores==="string"?search.stores:""}),head:()=>({meta:[{title:"Оформление заявки — Евроторг Media"},{name:"description",content:"Выбор услуг, торговых объектов и периода рекламной кампании."},{property:"og:title",content:"Оформление заявки — Евроторг Media"},{property:"og:description",content:"Оформите заявку на рекламу в торговой сети Евроторг."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:OrderPage});
function OrderPage(){const {stores:initialStores}=Route.useSearch();const navigate=useNavigate();const {user,createRequest}=usePortal();const [selectedServices,setSelectedServices]=useState<string[]>([]);const [selectedStores,setSelectedStores]=useState<string[]>(()=>initialStores.split(",").filter((id)=>STORES.some((s)=>s.id===id)).slice(0,12));const [from,setFrom]=useState("");const [to,setTo]=useState("");const [step,setStep]=useState<"period"|"services"|"stores">("period");const [query,setQuery]=useState("");const [format,setFormat]=useState<"list"|"matrix">("list");const [showPicker,setShowPicker]=useState(false);
const services=useMemo(()=>PLACEMENTS.filter((p)=>`${p.name} ${p.description}`.toLocaleLowerCase("ru").includes(query.trim().toLocaleLowerCase("ru"))),[query]);const chosen=PLACEMENTS.filter((p)=>selectedServices.includes(p.id));const items:RequestItem[]=chosen.flatMap((p)=>p.kind==="online"?[{placementId:p.id,placementName:p.name,storeId:"online",storeAddress:"Онлайн-канал",price:p.price}]:selectedStores.flatMap((id)=>{const s=STORES.find((v)=>v.id===id);return s?[{placementId:p.id,placementName:p.name,storeId:s.id,storeAddress:`${s.address} · ${s.format} · ${s.number}`,price:p.price}]:[]}));const total=items.some((i)=>i.price===null)?null:items.reduce((sum,i)=>sum+(i.price??0),0);const toggleService=(id:string)=>setSelectedServices((v)=>v.includes(id)?v.filter((x)=>x!==id):[...v,id]);const submit=()=>{if(!from||!to||to<from){toast.error("Укажите корректный период кампании");setStep("period");return;}if(!chosen.length){toast.error("Выберите рекламную услугу");setStep("services");return;}if(chosen.some((p)=>p.kind!=="online")&&!selectedStores.length){toast.error("Выберите торговый объект");setStep("stores");return;}const req=createRequest({items,periodFrom:from,periodTo:to,org:user?.org??"—",source:"portal"});toast.success(`Заявка ${req.number} отправлена`);navigate({to:"/requests"});};return <AppShell><div className="mb-3 text-xs text-muted-foreground"><Link to="/ads">Главная</Link> / Оформление заявки</div><div className="mb-5 flex flex-wrap items-center justify-between gap-4 border-b border-border pb-5"><div><h1 className="text-3xl font-bold">Оформление заявки</h1><div className="mt-2 flex gap-2">{(["period","services","stores"] as const).map((s,i)=><Button key={s} size="sm" variant={step===s?"default":"ghost"} onClick={()=>setStep(s)}>{i+1}. {s==="period"?"Период":s==="services"?"Услуги":"Объекты"}</Button>)}</div></div><div className="text-right"><p className="text-sm font-bold">Итого: {formatMoney(total)}</p><p className="text-xs text-muted-foreground">{items.length} позиций</p><Button className="mt-2 bg-success text-card hover:bg-success/90" onClick={submit}>Отправить заявку</Button></div></div>
{step==="period"&&<div className="mx-auto max-w-lg py-12 text-center"><h2 className="text-xl font-bold">Выберите период рекламной кампании</h2><div className="mt-8 grid grid-cols-2 gap-4 text-left"><label className="text-sm font-semibold">Начало<input aria-label="Начало периода" type="date" value={from} onChange={(e)=>setFrom(e.target.value)} className="mt-2 w-full rounded border border-input p-3"/></label><label className="text-sm font-semibold">Окончание<input aria-label="Окончание периода" type="date" min={from} value={to} onChange={(e)=>setTo(e.target.value)} className="mt-2 w-full rounded border border-input p-3"/></label></div><Button className="mt-8" onClick={()=>{if(!from||!to||to<from){toast.error("Укажите корректный период кампании");return;}setStep("services")}}>Далее</Button></div>}
{step==="services"&&<div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><aside><h2 className="mb-4 text-sm font-bold">Выберите рекламные услуги</h2><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Поиск услуги" aria-label="Поиск услуги" className="w-full rounded border border-input p-2 text-sm"/><p className="mt-4 text-xs text-muted-foreground">Выбрано: {selectedServices.length}</p><Button className="mt-4 w-full" onClick={()=>setStep("stores")}>Продолжить</Button></aside><div className="divide-y divide-border border-y border-border">{services.map((p)=><label key={p.id} className="flex cursor-pointer flex-wrap items-center gap-4 py-4 hover:bg-muted/50"><input type="checkbox" checked={selectedServices.includes(p.id)} onChange={()=>toggleService(p.id)} className="ml-2 size-4"/><img src={retailImage} width={1200} height={800} loading="lazy" alt="Рекламный формат" className="h-20 w-28 object-cover"/><span className="min-w-48 flex-1"><strong className="block text-sm">{p.name}</strong><span className="line-clamp-2 text-xs text-muted-foreground">{p.description}</span></span><strong className="mr-3 text-sm">{formatMoney(p.price)}</strong><ChevronDown className="mr-2 size-4"/></label>)}{!services.length&&<p className="p-6 text-sm text-muted-foreground">Услуги не найдены.</p>}</div></div>}
{step==="stores"&&<div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Торговые объекты</h2><p className="text-xs text-muted-foreground">Выберите магазины для выбранных услуг</p></div><div className="flex gap-2"><Button variant={format==="list"?"default":"outline"} size="sm" onClick={()=>setFormat("list")}>Адреса</Button><Button variant={format==="matrix"?"default":"outline"} size="sm" onClick={()=>setFormat("matrix")}>Матрица</Button><Button variant="outline" size="sm" onClick={()=>setShowPicker(true)}>Добавить торговые объекты</Button></div></div>{format==="list"?<StorePicker selected={selectedStores} onChange={setSelectedStores}/>:<div className="overflow-x-auto border border-border"><table className="w-full min-w-[640px] text-sm"><thead className="bg-muted text-left"><tr><th className="p-3">Торговый объект</th>{chosen.map((p)=><th key={p.id} className="p-3">{p.name}</th>)}</tr></thead><tbody>{selectedStores.map((id)=>{const s=STORES.find((v)=>v.id===id);return s?<tr key={id} className="border-t border-border"><td className="p-3">{s.address} · {s.format}</td>{chosen.map((p)=><td key={p.id} className="p-3"><Check className="size-4 text-success"/> {formatMoney(p.price)}</td>)}</tr>:null})}</tbody></table>{selectedStores.length===0&&<p className="p-5 text-sm text-muted-foreground">Выберите торговые объекты.</p>}</div>}</div>}
{showPicker&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/50 p-4" role="dialog" aria-modal="true" aria-label="Добавить торговые объекты"><div className="max-h-[90vh] w-full max-w-4xl overflow-y-auto bg-card p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">Торговые объекты</h2><Button variant="ghost" size="icon" onClick={()=>setShowPicker(false)} aria-label="Закрыть"><Trash2 className="size-4"/></Button></div><StorePicker selected={selectedStores} onChange={setSelectedStores}/><div className="mt-5 text-right"><Button onClick={()=>setShowPicker(false)}>Применить выбор</Button></div></div></div>}
<div className="mt-8 flex items-center justify-between border-t border-border pt-4"><Button variant="ghost" asChild><Link to="/services"><ArrowLeft/> Каталог услуг</Link></Button><Button onClick={submit}><ShoppingCart/> Отправить заявку</Button></div>
</AppShell>}
