import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/portal/AppShell";
import { RequestDialog } from "@/components/portal/RequestDialog";
import { PLACEMENTS, formatMoney } from "@/lib/portal/data";
import retailImage from "@/assets/retail-placement.jpg";
export const Route = createFileRoute("/services/$serviceId")({ loader: ({params}) => {const service=PLACEMENTS.find((p)=>p.id===params.serviceId);if(!service)throw notFound();return service;}, head: ({loaderData}) => ({meta:[{title:`${loaderData?.name ?? "Услуга"} — Евроторг Media`},{name:"description",content:loaderData?.description ?? "Рекламная услуга Евроторг Media"},{property:"og:title",content:`${loaderData?.name ?? "Услуга"} — Евроторг Media`},{property:"og:description",content:loaderData?.description ?? "Рекламная услуга Евроторг Media"},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:ServicePage });
function ServicePage(){const p=Route.useLoaderData();const [open,setOpen]=useState(false);return <AppShell><div className="mb-5 text-xs text-muted-foreground"><Link to="/ads">Главная</Link> / <Link to="/services">Рекламные услуги</Link> / {p.name}</div><h1 className="mb-5 text-3xl font-bold">{p.name}</h1><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(280px,1fr)]"><img src={retailImage} width={1200} height={800} alt="Размещение рекламы в магазине" className="aspect-[4/3] w-full object-cover"/><div><p className="text-sm leading-7">{p.description}</p><p className="mt-6 border-t border-border pt-5 text-sm font-bold">Стоимость: {formatMoney(p.price)}</p><Button className="mt-5" onClick={()=>setOpen(true)}>Добавить в заявку</Button></div></div><div className="mt-12 border-t border-border pt-7"><h2 className="text-xl font-bold">Доступные торговые объекты</h2><p className="mt-2 text-sm text-muted-foreground">Выберите магазины и период размещения при оформлении заявки.</p><Button variant="outline" className="mt-5" asChild><Link to="/stores" search={{ query: "", format: "" }}>Посмотреть объекты</Link></Button></div><RequestDialog placement={p} open={open} onClose={()=>setOpen(false)}/></AppShell>}
